### ISSUE TITLE
Report where the illegal transitive type dependency was found

### ISSUE THREAD

**Issue by rnc** [ImmobilienScout24/illegal-transitive-dependency-check#27]
Is it possible when reporting e.g. 
Found 29 illegal transitive type dependencies in artifact ...
1.) ...

To report which jar in the classpath it was resolving them from ?

**Comment by 2bad4u** [comment]
Currently the check does the following:
a) Load all types from the classes in the current Maven project's target and scans their dependencies
b) Scan all type names from all artifacts declared as dependency
c) Remove all types from the list (a) that are either declared in the project itself or found in b)
d) list the remaining type names as transitive dependencies

This approach is quite simple and fast but naturally provides no information about the artifacts the missing types would be actually loaded from. To get this information all (transitive) dependencies have to be resolved and scanned for class names - which would be really slow..

Anyhow it's not impossible I'll should look into that..

**Comment by 2bad4u** [comment]
Works with release 1.7.3. If `listMissingArtifacts` is set the transitively used classes will be shown with their respective artifacts.
